CHAPTER 2
An Array of Sequences

In [4]:
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[36, 162, 163, 165, 8364, 164]

In [5]:
symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

In [6]:
x = 'ABC'
codes = [ord(x) for x in x]

In [7]:
codes

[65, 66, 67]

Listcomps Versus map and filter

In [8]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))

In [9]:
beyond_ascii

[162, 163, 165, 8364, 164]

In [10]:
beyond_ascii

[162, 163, 165, 8364, 164]

Cartesian Products

In [12]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [13]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [14]:
tshirts = [(color, size) for size in sizes for color in colors]

In [15]:
tshirts 

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

In [16]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in (f'{c} {s}' for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


Example 2-7. Tuples used as records

In [17]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'),('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [18]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [19]:
a= (10, 'alpha', [1, 2])
b = (10, 'alpha', [1, 2])
a == b

True

In [20]:
b[-1].append(99)

In [21]:
a == b

False

In [22]:
b

(10, 'alpha', [1, 2, 99])

In [23]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True

tf = (10, 'alpha', (1, 2))
tm = (10, 'alpha', [1, 2])
fixed(tf)

True

Unpacking Sequences and Iterables

In [24]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates # unpacking
latitude

33.9425

In [25]:
longitude

-118.408056

In [26]:
divmod(20, 8)

(2, 4)

In [27]:
t = (20, 8)
divmod(*t)

(2, 4)

In [28]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

Using * to Grab Excess Items

In [30]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [32]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [33]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [45]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [46]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

Unpacking with * in Function Calls and Sequence Literals

In [43]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

In [44]:
fun(*[1, 2], 3, *range(4, 7))

(1, 2, 3, 4, (5, 6))

In [40]:
*range(4), 4

(0, 1, 2, 3, 4)

In [41]:
[*range(4), 4]

[0, 1, 2, 3, 4]

In [42]:
{*range(4), 4, *(5, 6, 7)}

{0, 1, 2, 3, 4, 5, 6, 7}

Nested Unpacking

In [39]:
metro_areas = [
('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for name, _, _, (lat, lon) in metro_areas:
        if lon <= 0:
            print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')
if __name__ == '__main__':
    main()


                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


In [35]:
metro_areas = [
('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for record in metro_areas:
        match record:
            case [name, _, _, (lat, lon)] if lon <= 0:
                print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

In [37]:
main()

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


Slicing

In [48]:
l = [10, 20, 30, 40, 50, 60]
l[:2] # split at 2

[10, 20]

In [49]:
l[2:]

[30, 40, 50, 60]

In [50]:
l[:3] # split at 3

[10, 20, 30]

In [51]:
l[3:]

[40, 50, 60]

Slice Objects

In [52]:
s = 'bicycle'
s[::3]

'bye'

In [53]:
s[::-1]

'elcycib'

In [54]:
s[::-2]

'eccb'

In [55]:
invoice = """
... 0.....6.................................40........52...55........
... 1909 Pimoroni PiBrella $17.50 3 $52.50
... 1489 6mm Tactile Switch x20 $4.95 2 $9.90
... 1510 Panavise Jr. - PV-201 $28.00 1 $28.00
... 1601 PiTFT Mini Kit 320x240 $34.95 1 $34.95
... """
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

 imoroni PiBrella $17.50 3 $52.50
0 mm Tactile Switch x20 $4.95 2 $9.9
00 anavise Jr. - PV-201 $28.00 1 $28.
.95 iTFT Mini Kit 320x240 $34.95 1 $34
 


Assigning to Slices

In [56]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:

l[2:5] = [20, 30]
l

[0, 1, 20, 30, 6, 7, 8, 9]

In [60]:
del l[5:7]
l

[0, 1, 20, 30, 6]

In [61]:
l[3::2] = [11, 22]
l

ValueError: attempt to assign sequence of size 2 to extended slice of size 1

In [62]:
l[2:5] = 100
l

TypeError: can only assign an iterable

In [63]:
l[2:5] = [100]
l

[0, 1, 100]

Using + and * with Sequences

In [64]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [65]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

Building Lists of Lists

In [66]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [72]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [70]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [71]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [73]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

In [74]:
board 

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [101]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [102]:
board[2][0] = 'X'

In [103]:
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [104]:
l = [1, 2, 3]
id(l)

2359411372032

In [105]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [106]:
id(l)

2359411372032

In [ ]:
t = (1, 2, 3)
id(t)

In [107]:
t *= 2
id(t)

2359380375200

A += Assignment Puzzler

In [47]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [92]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [93]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [94]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [97]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [98]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [99]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [100]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

Arrays

In [108]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.6953317467654465

In [ ]:
floats

Memory Views

In [ ]:
from array import array
octets = array('B', range(6))

In [ ]:
>>> m1 = memoryview(octets)
>>> m1.tolist()
[0, 1, 2, 3, 4, 5]
>>> m2 = m1.cast('B', [2, 3])
>>> m2.tolist()
[[0, 1, 2], [3, 4, 5]]
>>> m3 = m1.cast('B', [3, 2])
>>> m3.tolist()
[[0, 1], [2, 3], [4, 5]]
>>> m2[1,1] = 22
>>> m3[1,1] = 33
>>> octets
array('B', [0, 1, 2, 33, 22, 5])

In [ ]:
>>> numbers = array.array('h', [-2, -1, 0, 1, 2])
>>> memv = memoryview(numbers)
>>> len(memv)
5
>>> memv[0]
-2
>>> memv_oct = memv.cast('B')
>>> memv_oct.tolist()
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
>>> memv_oct[5] = 4
>>> numbers
array('h', [-2, -1, 1024, 1, 2])

NumPy

In [84]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
type(a)

numpy.ndarray

In [86]:
a.shape

(12,)

In [87]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a[2]

array([ 8,  9, 10, 11])

In [89]:
a[2, 1]

9

In [90]:
a[:, 1]

array([1, 5, 9])

In [91]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Deques and Other Queues

In [78]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [79]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [80]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [81]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [82]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [83]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)